In [1]:
print("hello")

hello

In [2]:
import pandas as pd
print(pd.__version__)

3.0.5

In [3]:
import nltk
print("NLTK working!")

NLTK working!

In [4]:
import re

In [5]:
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package stopwords to C:\Users\Rahath
[nltk_data]     farheen\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to C:\Users\Rahath
[nltk_data]     farheen\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to C:\Users\Rahath
[nltk_data]     farheen\AppData\Roaming\nltk_data...

True

In [6]:
df = pd.read_csv("../data/processed_news.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (38646, 7)

,title,text,subject,date,label,text_length,content
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,1028,Ben Stein Calls Out 9th Circuit Court: Committ...
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,4820,Trump drops Steve Bannon from National Securit...
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,1848,Puerto Rico expects U.S. to lift Jones Act shi...
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,1244,OOPS: Trump Just Accidentally Confirmed He Le...
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,3137,Donald Trump heads for Scotland to reopen a go...

In [7]:
print(df["content"].iloc[0])

Ben Stein Calls Out 9th Circuit Court: Committed a ‘Coup d’état’ Against the Constitution 21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV

In [8]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [9]:
sample_text = df["content"].iloc[0]

print("BEFORE:")
print(sample_text)

print("\nAFTER:")
print(clean_text(sample_text))

BEFORE:
Ben Stein Calls Out 9th Circuit Court: Committed a ‘Coup d’état’ Against the Constitution 21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV

AFTER:
ben stein calls out th circuit court committed a coup dtat against the constitution st century wire says ben stein reputable professor from pepperdine university also of some hollywood fame appearing in tv shows and films such as ferris bueller s day off made some provocative statements on judge jeanine pirro s show recently while discussing the halt that was imposed on president trump s executive order on travel stein referred to the judgement by the th circuit court in washington state as a coup d tat against the executive branch and against the constitution stein went on to call the judges in seattle political puppets and the judiciary political pawns watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the executive orderread more trump news at st century wire trump filessupport our work by subscribing becoming a member wiretv

In [10]:
df["clean_text"] = df["content"].apply(clean_text)

In [11]:
df[["content", "clean_text"]].head()

,content,clean_text
0,Ben Stein Calls Out 9th Circuit Court: Committ...,ben stein calls out th circuit court committed...
1,Trump drops Steve Bannon from National Securit...,trump drops steve bannon from national securit...
2,Puerto Rico expects U.S. to lift Jones Act shi...,puerto rico expects us to lift jones act shipp...
3,OOPS: Trump Just Accidentally Confirmed He Le...,oops trump just accidentally confirmed he leak...
4,Donald Trump heads for Scotland to reopen a go...,donald trump heads for scotland to reopen a go...

In [12]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

print("Number of stopwords:", len(stop_words))
print(list(stop_words)[:20])

Number of stopwords: 198
['too', 'such', 'shouldn', "we're", 'shan', 'hasn', "he'll", 'him', 'further', "haven't", 'am', 'during', "we'd", 'or', 'ourselves', 'will', 'and', 'her', "i've", 'those']

In [13]:
def remove_stopwords(text):
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

In [14]:
sample = df["clean_text"].iloc[0]

print("BEFORE:")
print(sample)

print("\nAFTER:")
print(remove_stopwords(sample))

BEFORE:
ben stein calls out th circuit court committed a coup dtat against the constitution st century wire says ben stein reputable professor from pepperdine university also of some hollywood fame appearing in tv shows and films such as ferris bueller s day off made some provocative statements on judge jeanine pirro s show recently while discussing the halt that was imposed on president trump s executive order on travel stein referred to the judgement by the th circuit court in washington state as a coup d tat against the executive branch and against the constitution stein went on to call the judges in seattle political puppets and the judiciary political pawns watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the executive orderread more trump news at st century wire trump filessupport our work by subscribing becoming a member wiretv

AFTER:
ben stein calls th circuit court committed coup dtat constitution st century wire says ben stein reputable professor pepperdine university also hollywood fame appearing tv shows films ferris bueller day made provocative statements judge jeanine pirro show recently discussing halt imposed president trump executive order travel stein referred judgement th circuit court washington state coup tat executive branch constitution stein went call judges seattle political puppets judiciary political pawns watch interview complete statements note stark contrast rhetoric leftist media pundits neglect note court ever blocked presidential orders immigration past discuss legal efficacy halt actual text executive orderread trump news st century wire trump filessupport work subscribing becoming member wiretv

In [15]:
df["no_stopwords"] = df["clean_text"].apply(remove_stopwords)

In [16]:
df[["clean_text", "no_stopwords"]].head()

,clean_text,no_stopwords
0,ben stein calls out th circuit court committed...,ben stein calls th circuit court committed cou...
1,trump drops steve bannon from national securit...,trump drops steve bannon national security cou...
2,puerto rico expects us to lift jones act shipp...,puerto rico expects us lift jones act shipping...
3,oops trump just accidentally confirmed he leak...,oops trump accidentally confirmed leaked israe...
4,donald trump heads for scotland to reopen a go...,donald trump heads scotland reopen golf resort...

In [17]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [18]:
def lemmatize_text(text):
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [19]:
sample = df["no_stopwords"].iloc[0]

print("BEFORE:")
print(sample)

print("\nAFTER:")
print(lemmatize_text(sample))

BEFORE:
ben stein calls th circuit court committed coup dtat constitution st century wire says ben stein reputable professor pepperdine university also hollywood fame appearing tv shows films ferris bueller day made provocative statements judge jeanine pirro show recently discussing halt imposed president trump executive order travel stein referred judgement th circuit court washington state coup tat executive branch constitution stein went call judges seattle political puppets judiciary political pawns watch interview complete statements note stark contrast rhetoric leftist media pundits neglect note court ever blocked presidential orders immigration past discuss legal efficacy halt actual text executive orderread trump news st century wire trump filessupport work subscribing becoming member wiretv

AFTER:
ben stein call th circuit court committed coup dtat constitution st century wire say ben stein reputable professor pepperdine university also hollywood fame appearing tv show film ferris bueller day made provocative statement judge jeanine pirro show recently discussing halt imposed president trump executive order travel stein referred judgement th circuit court washington state coup tat executive branch constitution stein went call judge seattle political puppet judiciary political pawn watch interview complete statement note stark contrast rhetoric leftist medium pundit neglect note court ever blocked presidential order immigration past discus legal efficacy halt actual text executive orderread trump news st century wire trump filessupport work subscribing becoming member wiretv

In [20]:
df["processed_text"] = df["no_stopwords"].apply(lemmatize_text)

print("Lemmatization completed!")

Lemmatization completed!

In [21]:
display(df[["no_stopwords", "processed_text"]].head())

,no_stopwords,processed_text
0,ben stein calls th circuit court committed cou...,ben stein call th circuit court committed coup...
1,trump drops steve bannon national security cou...,trump drop steve bannon national security coun...
2,puerto rico expects us lift jones act shipping...,puerto rico expects u lift jones act shipping ...
3,oops trump accidentally confirmed leaked israe...,oops trump accidentally confirmed leaked israe...
4,donald trump heads scotland reopen golf resort...,donald trump head scotland reopen golf resort ...

In [22]:
sample = df["content"].iloc[0]

print("ORIGINAL:")
print(sample)

print("\n" + "="*80 + "\n")

print("PROCESSED:")
print(df["processed_text"].iloc[0])

ORIGINAL:
Ben Stein Calls Out 9th Circuit Court: Committed a ‘Coup d’état’ Against the Constitution 21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV

================================================================================

PROCESSED:
ben stein call th circuit court committed coup dtat constitution st century wire say ben stein reputable professor pepperdine university also hollywood fame appearing tv show film ferris bueller day made provocative statement judge jeanine pirro show recently discussing halt imposed president trump executive order travel stein referred judgement th circuit court washington state coup tat executive branch constitution stein went call judge seattle political puppet judiciary political pawn watch interview complete statement note stark contrast rhetoric leftist medium pundit neglect note court ever blocked presidential order immigration past discus legal efficacy halt actual text executive orderread trump news st century wire trump filessupport work subscribing becoming member wiretv

In [23]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (38646, 10)

Columns:
['title', 'text', 'subject', 'date', 'label', 'text_length', 'content', 'clean_text', 'no_stopwords', 'processed_text']

In [24]:
df.to_csv("../data/processed_news_nlp.csv", index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!